# Generated by Django 4.2.1 on 2023-06-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('text', models.TextField()),
                ('time_field', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=55)),
                ('name_ru', models.CharField(max_length=55)),
                ('country_uz', models.CharField(max_length=55)),
                ('country_ru', models.CharField(max_length=55)),
                ('region_uz', models.CharField(max_length=55)),
                ('region_ru', models.CharField(max_length=55)),
                ('city_uz', models.CharField(max_length=55)),
                ('city_ru', models.CharField(max_length=55)),
                ('district_uz', models.CharField(blank=True, max_length=55, null=True)),
                ('district_ru', models.CharField(blank=True, max_length=55, null=True)),
                ('street_uz', models.CharField(max_length=55)),
                ('street_ru', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=55)),
                ('name_ru', models.CharField(max_length=55)),
                ('initial_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('sale', models.FloatField(default=0)),
                ('depozit', models.FloatField(blank=True, null=True)),
                ('fuel_consumption', models.FloatField()),
                ('year', models.IntegerField()),
                ('distance', models.FloatField(default=0)),
                ('engine', models.FloatField()),
                ('colour_uz', models.CharField(max_length=25)),
                ('colour_ru', models.CharField(max_length=25)),
                ('views', models.IntegerField(default=0)),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('engine_power', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='CarDefectImages')),
                ('image2', models.ImageField(upload_to='CarDefectImages')),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarEnginePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=55)),
                ('name_ru', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CarFuelSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=55)),
                ('name_ru', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CarGarantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=55)),
                ('name_ru', models.CharField(max_length=55)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarGearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=55)),
                ('name_ru', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CarHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=55)),
                ('name_ru', models.CharField(max_length=55)),
                ('initial_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('sale', models.FloatField(default=0)),
                ('depozit', models.FloatField(blank=True, null=True)),
                ('fuel_consumption', models.FloatField()),
                ('year', models.IntegerField()),
                ('distance', models.FloatField(default=0)),
                ('engine', models.FloatField()),
                ('engine_power', models.FloatField(blank=True, null=True)),
                ('colour_uz', models.CharField(max_length=25)),
                ('colour_ru', models.CharField(max_length=25)),
                ('views', models.IntegerField(default=0)),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='CarsImages')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='CarImages')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=55)),
                ('name_ru', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CarPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=55)),
                ('name_ru', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CarSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=55)),
                ('name_ru', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('visit_time', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.branch')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
