# Generated by Django 4.2.1 on 2023-05-22 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('country', models.CharField(max_length=55)),
                ('region', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('district', models.CharField(blank=True, max_length=55, null=True)),
                ('street', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('initial_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('sale', models.FloatField(default=0)),
                ('depozit', models.FloatField(blank=True, null=True)),
                ('fuel_consumption', models.FloatField()),
                ('year', models.IntegerField()),
                ('distance', models.FloatField(default=0)),
                ('engine', models.FloatField()),
                ('colour', models.CharField(max_length=25)),
                ('views', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.branch')),
            ],
        ),
        migrations.CreateModel(
            name='CarDefectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='CarImages')),
            ],
        ),
        migrations.CreateModel(
            name='CarFuelSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CarGarantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarGearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='CarImages')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='CarSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CarPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carseries')),
            ],
        ),
        migrations.CreateModel(
            name='CarDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('image', models.ManyToManyField(to='cars.cardefectimages')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carfuelsort'),
        ),
        migrations.AddField(
            model_name='car',
            name='garant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cargaranttype'),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cargearbox'),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ManyToManyField(to='cars.carimages'),
        ),
        migrations.AddField(
            model_name='car',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carposition'),
        ),
    ]
