# Generated by Django 4.2.1 on 2023-05-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardefect',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
