# Generated by Django 4.2.1 on 2023-07-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_order_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.IntegerField(max_length=13)),
                ('message', models.TextField()),
            ],
        ),
    ]
