# Generated by Django 4.2.1 on 2023-05-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
