# Generated by Django 4.2.1 on 2023-07-11 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_calltouser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-views']},
        ),
        migrations.AlterModelOptions(
            name='carposition',
            options={'ordering': ['-position']},
        ),
        migrations.AlterModelOptions(
            name='carseries',
            options={'ordering': ['-series__position__views']},
        ),
        migrations.AddField(
            model_name='car',
            name='usd_currency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='cars.carposition'),
        ),
        migrations.AlterField(
            model_name='carposition',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='cars.carseries'),
        ),
    ]
