# Generated by Django 4.2.1 on 2023-07-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_options_alter_carposition_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='usd_currency',
            new_name='usd_price',
        ),
    ]
