# Generated by Django 4.2.1 on 2023-06-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_car_image_carimages_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
