# Generated by Django 4.2.1 on 2023-07-11 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename_usd_currency_car_usd_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='usd_price',
            new_name='sum_price',
        ),
    ]
