# Generated by Django 4.2.1 on 2023-06-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_comment_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
