# Generated by Django 4.2.1 on 2023-07-18 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0009_rename_usd_price_car_sum_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='liked_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
