# Generated by Django 4.2.1 on 2023-06-02 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_comment_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_sort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carfuelsort'),
        ),
        migrations.AlterField(
            model_name='car',
            name='garant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cargaranttype'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cargearbox'),
        ),
        migrations.AlterField(
            model_name='cardefectimages',
            name='image',
            field=models.ImageField(upload_to='CarDefectImages'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='image',
            field=models.FileField(upload_to='CarsImages'),
        ),
    ]
