# Generated by Django 4.2.1 on 2023-06-02 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_fuel_sort_alter_car_garant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('initial_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('sale', models.FloatField(default=0)),
                ('depozit', models.FloatField(blank=True, null=True)),
                ('fuel_consumption', models.FloatField()),
                ('year', models.IntegerField()),
                ('distance', models.FloatField(default=0)),
                ('engine', models.FloatField()),
                ('colour', models.CharField(max_length=25)),
                ('views', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.branch')),
                ('fuel_sort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carfuelsort')),
                ('garant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cargaranttype')),
                ('gearbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cargearbox')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carposition')),
            ],
        ),
    ]
