# Generated by Django 4.2.1 on 2023-06-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_carhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimages',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='CarImages'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='image',
            field=models.ImageField(upload_to='CarsImages'),
        ),
    ]
