# Generated by Django 4.2.1 on 2023-10-11 07:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0011_remove_car_liked_users_liked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liked',
            unique_together={('car', 'user')},
        ),
    ]
