# Generated by Django 4.2.1 on 2023-06-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_carimages_image_file_alter_carimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardefect',
            name='image',
        ),
        migrations.AddField(
            model_name='cardefect',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='CarImages'),
        ),
        migrations.AddField(
            model_name='cardefect',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='CarImages'),
        ),
        migrations.DeleteModel(
            name='CarDefectImages',
        ),
    ]
