# Generated by Django 4.2.1 on 2023-06-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_remove_cardefect_image_cardefect_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardefect',
            name='image1',
            field=models.ImageField(upload_to='CarImages'),
        ),
        migrations.AlterField(
            model_name='cardefect',
            name='image2',
            field=models.ImageField(upload_to='CarImages'),
        ),
    ]
