# Generated by Django 4.2.1 on 2023-05-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
