# Generated by Django 4.2.1 on 2023-05-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_comment_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='branch',
        ),
    ]
